repos:
  - hooks:
      - id: codesorter
    repo: https://github.com/praw-dev/CodeSorter
    rev: v0.2.7
  - hooks:
      - args: [--fix]
        id: ruff-check
      - id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.16
