name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: bboe/.github/.github/workflows/pypi-publish.yml@main
